server {
    listen 80 default_server;
    listen [::]:80 ipv6only=on default_server;
    server_name cfp.eurofurence.org;

    location / {
        proxy_pass http://pretalx-web:8088/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host cfp.eurofurence.org;
    }

    location /media/ {
      alias /usr/share/nginx/pretalx/media/;
      add_header Content-Disposition 'attachment; filename="$1"';
      expires 7d;
      access_log off;
    }

    location /static/ {
      alias /usr/share/nginx/pretalx/static/;
      add_header Content-Disposition 'attachment; filename="$1"';
      expires 7d;
      access_log off;
    }

}

